/* Autogenerated file, overwritten by uNmINeD on map generation. */
var UnminedMapProperties = {
    minZoom: -5,
    maxZoom: 2,
    defaultZoom: 0,
    imageFormat: "jpeg",
    minRegionX: -8,
    minRegionZ: -25,
    maxRegionX: 22,
    maxRegionZ: 57,
    worldName: "world",
    background: "",
    markers: new Array(),
    enableGrid: true,
    showGrid: true,
    centerX: 0,
    centerZ: 0
}
