/* Autogenerated file, overwritten by uNmINeD on map generation. */
var UnminedMapProperties = {
    minZoom: -5,
    maxZoom: 2,
    defaultZoom: 0,
    imageFormat: "jpeg",
    minRegionX: -11,
    minRegionZ: -11,
    maxRegionX: 11,
    maxRegionZ: 11,
    worldName: "paper_1_21_1_2972731",
    background: "",
    markers: new Array(),
    enableGrid: true,
    showGrid: true,
    centerX: 0,
    centerZ: 0
}
